[theme]
base="dark"
primaryColor="#1999dd" 
backgroundColor="#000000"
secondaryBackgroundColor="#111111"
textColor="#FFFFFF"

[client]
toolbarMode = 'minimal'
showSidebarNavigation = true

[server]
maxUploadSize = 2